global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ten-slots-app1
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app1:8080' ]

  - job_name: ten-slots-app2
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'app2:8080' ]
